# Start from the metabase container
FROM metabase/metabase:v0.40.5

ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache binutils groff less python3 curl jq ca-certificates && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools awscli

COPY ./infra/start-metabase.sh /root/start-metabase.sh
RUN chmod 755 /root/start-metabase.sh

EXPOSE 3000
ENTRYPOINT ["/root/start-metabase.sh"]
